### ISSUE TITLE
학습 중 에러 발생 건

### ISSUE THREAD

**Issue by hongyongje** [Kisane-Project/object-detection#1]
1) 전체 로그 파일
    - [Issue_20230116.txt](https://github.com/Kisane-Project/object-detection/files/10430172/Issue_20230116.txt)

2) 세팅
    cfg.SOLVER.IMS_PER_BATCH = 16
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = (128)

3) 내용
    - 아래와 같이 학습 중 에러 발생
       ERROR [01/16 19:40:39 d2.engine.train_loop]: Exception during training:

```
<생략>

[01/16 19:40:37 d2.evaluation.evaluator]: Inference done 19292/19310. Dataloading: 0.0008 s/iter. Inference: 0.0630 s/iter. Eval: 0.0001 s/iter. Total: 0.0640 s/iter. ETA=0:00:01
[01/16 19:40:38 d2.evaluation.evaluator]: Total inference time: 0:20:34.892340 (0.063967 s / iter per device, on 1 devices)
[01/16 19:40:38 d2.evaluation.evaluator]: Total inference pure compute time: 0:20:16 (0.063005 s / iter per device, on 1 devices)
[01/16 19:40:39 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[01/16 19:40:39 d2.evaluation.coco_evaluation]: Saving results to /home/kisan-dl-admin/kisan/AI_Scanner/gist/hdd1_data/datas/kisane_DB/train_results/inference/coco_instances_results.json
[01/16 19:40:39 d2.evaluation.coco_evaluation]: Evaluating predictions with official COCO API...
Loading and preparing results...
ERROR [01/16 19:40:39 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/train_loop.py", line 150, in train
    self.after_step()
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/train_loop.py", line 180, in after_step
    h.after_step()
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/hooks.py", line 556, in after_step
    self._do_eval()
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/hooks.py", line 529, in _do_eval
    results = self._func()
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/defaults.py", line 453, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/defaults.py", line 617, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/evaluation/evaluator.py", line 204, in inference_on_dataset
    results = evaluator.evaluate()
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/evaluation/coco_evaluation.py", line 206, in evaluate
    self._eval_predictions(predictions, img_ids=img_ids)
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/evaluation/coco_evaluation.py", line 266, in _eval_predictions
    _evaluate_predictions_on_coco(
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/evaluation/coco_evaluation.py", line 590, in _evaluate_predictions_on_coco
    coco_dt = coco_gt.loadRes(coco_results)
  File "/home/kisan-dl-admin/anaconda3/envs/kisan_electronics/lib/python3.9/site-packages/pycocotools/coco.py", line 327, in loadRes
    assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set
[01/16 19:40:39 d2.engine.hooks]: Overall training speed: 997 iterations in 0:33:07 (1.9937 s / it)
[01/16 19:40:39 d2.engine.hooks]: Total training time: 0:53:57 (0:20:49 on hooks)
[01/16 19:40:39 d2.utils.events]:  eta: 2 days, 6:45:42  iter: 999  total_loss: 0.4045  loss_cls: 0.05512  loss_box_reg: 0.3157  loss_rpn_cls: 0.007528  loss_rpn_loc: 0.02677  time: 1.9917  data_time: 0.4004  lr: 0.000999  max_mem: 19770M
Traceback (most recent call last):
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/train.py", line 196, in <module>
    launch(
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/train.py", line 185, in main
    return trainer.train()
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/train_loop.py", line 150, in train
    self.after_step()
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/train_loop.py", line 180, in after_step
    h.after_step()
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/hooks.py", line 556, in after_step
    self._do_eval()
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/hooks.py", line 529, in _do_eval
    results = self._func()
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/defaults.py", line 453, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/engine/defaults.py", line 617, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/evaluation/evaluator.py", line 204, in inference_on_dataset
    results = evaluator.evaluate()
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/evaluation/coco_evaluation.py", line 206, in evaluate
    self._eval_predictions(predictions, img_ids=img_ids)
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/evaluation/coco_evaluation.py", line 266, in _eval_predictions
    _evaluate_predictions_on_coco(
  File "/home/kisan-dl-admin/kisan/AI_Scanner/gist/object-detection/detectron2/evaluation/coco_evaluation.py", line 590, in _evaluate_predictions_on_coco
    coco_dt = coco_gt.loadRes(coco_results)
  File "/home/kisan-dl-admin/anaconda3/envs/kisan_electronics/lib/python3.9/site-packages/pycocotools/coco.py", line 327, in loadRes
    assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set
Shutting down background jobs, please wait a moment...
Done!
Waiting for the remaining 71 operations to synchronize with Neptune. Do not kill this process.
All 71 operations synced, thanks for waiting!
Explore the metadata in the Neptune app:
https://app.neptune.ai/psh9002/kisan-electronics/e/KIS-121
```

**Comment by psh9002** [comment]
혹시 json 파일 재생성하실 때, `entire`, `train`, `val` json 파일을 모두 지웠다가 생성하셨을까요?
`[01/16 19:40:37 d2.evaluation.evaluator]: Inference done` 이 부분은 validation set에서 metric 산출을 위해 inference를 진행하는 것이 끝났다는 뜻인데, 이 후에 나오는 오류들을 보았을 때, image id 부분 매칭이 잘못된게 아닌가 싶습니다.
(`assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds()))`)

**Comment by yjhong-kisane** [comment]
~/kisane_DB/V0_0_1/LI3/ 경로의 
kisan_entire_dataset.json, 
kisan_train.json, 
kisan_val.json 
위 3개의 파일을 모두 삭제 하고 다시 생성하였습니다.

**Comment by psh9002** [comment]
일단 제 데스크탑에서는 validation 과정에서 따로 오류가 나진 않았습니다. 아래에 validation이 잘 이루어진 경우를 공유해드리겠습니다.

```
..... (생략)
[01/17 13:51:54 d2.evaluation.evaluator]: Inference done 11/993. Dataloading: 0.0006 s/iter. Inference: 0.0655 s/iter. Eval: 0.0001 s/iter. Total: 0.0662 s/iter. ETA=0:01:04
[01/17 13:51:59 d2.evaluation.evaluator]: Inference done 87/993. Dataloading: 0.0007 s/iter. Inference: 0.0653 s/iter. Eval: 0.0001 s/iter. Total: 0.0661 s/iter. ETA=0:00:59
[01/17 13:52:04 d2.evaluation.evaluator]: Inference done 163/993. Dataloading: 0.0007 s/iter. Inference: 0.0654 s/iter. Eval: 0.0001 s/iter. Total: 0.0662 s/iter. ETA=0:00:54
[01/17 13:52:09 d2.evaluation.evaluator]: Inference done 235/993. Dataloading: 0.0007 s/iter. Inference: 0.0665 s/iter. Eval: 0.0001 s/iter. Total: 0.0673 s/iter. ETA=0:00:51
[01/17 13:52:14 d2.evaluation.evaluator]: Inference done 304/993. Dataloading: 0.0007 s/iter. Inference: 0.0677 s/iter. Eval: 0.0001 s/iter. Total: 0.0686 s/iter. ETA=0:00:47
[01/17 13:52:19 d2.evaluation.evaluator]: Inference done 376/993. Dataloading: 0.0007 s/iter. Inference: 0.0679 s/iter. Eval: 0.0001 s/iter. Total: 0.0688 s/iter. ETA=0:00:42
[01/17 13:52:24 d2.evaluation.evaluator]: Inference done 450/993. Dataloading: 0.0008 s/iter. Inference: 0.0677 s/iter. Eval: 0.0001 s/iter. Total: 0.0686 s/iter. ETA=0:00:37
[01/17 13:52:29 d2.evaluation.evaluator]: Inference done 523/993. Dataloading: 0.0008 s/iter. Inference: 0.0678 s/iter. Eval: 0.0001 s/iter. Total: 0.0687 s/iter. ETA=0:00:32
[01/17 13:52:34 d2.evaluation.evaluator]: Inference done 598/993. Dataloading: 0.0008 s/iter. Inference: 0.0676 s/iter. Eval: 0.0001 s/iter. Total: 0.0685 s/iter. ETA=0:00:27
[01/17 13:52:39 d2.evaluation.evaluator]: Inference done 674/993. Dataloading: 0.0008 s/iter. Inference: 0.0674 s/iter. Eval: 0.0001 s/iter. Total: 0.0682 s/iter. ETA=0:00:21
[01/17 13:52:44 d2.evaluation.evaluator]: Inference done 747/993. Dataloading: 0.0008 s/iter. Inference: 0.0674 s/iter. Eval: 0.0001 s/iter. Total: 0.0683 s/iter. ETA=0:00:16
[01/17 13:52:49 d2.evaluation.evaluator]: Inference done 821/993. Dataloading: 0.0008 s/iter. Inference: 0.0674 s/iter. Eval: 0.0001 s/iter. Total: 0.0683 s/iter. ETA=0:00:11
[01/17 13:52:54 d2.evaluation.evaluator]: Inference done 894/993. Dataloading: 0.0008 s/iter. Inference: 0.0674 s/iter. Eval: 0.0001 s/iter. Total: 0.0683 s/iter. ETA=0:00:06
[01/17 13:52:59 d2.evaluation.evaluator]: Inference done 969/993. Dataloading: 0.0008 s/iter. Inference: 0.0673 s/iter. Eval: 0.0001 s/iter. Total: 0.0682 s/iter. ETA=0:00:01
[01/17 13:53:01 d2.evaluation.evaluator]: Total inference time: 0:01:07.380157 (0.068199 s / iter per device, on 1 devices)
[01/17 13:53:01 d2.evaluation.evaluator]: Total inference pure compute time: 0:01:06 (0.067275 s / iter per device, on 1 devices)
[01/17 13:53:01 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[01/17 13:53:01 d2.evaluation.coco_evaluation]: Saving results to /home/bak/Projects/Datasets/kisan_sample_data/train_results/inference/coco_instances_results.json
[01/17 13:53:01 d2.evaluation.coco_evaluation]: Evaluating predictions with official COCO API...
Loading and preparing results...
```
↑이 부분까지 홍용제 책임님과 같은 log를 띄워주며, 책임님의 경우 바로 다음 줄에 오류가 발생했습니다.
진행이 잘 이루어진 경우에는 아래처럼↓ 평가 metric이 나온 후,
```
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.22s).
Accumulating evaluation results...
DONE (t=0.04s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.639
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.782
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.639
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.711
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.711
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.711
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.711
[01/17 13:53:01 d2.evaluation.coco_evaluation]: Evaluation results for bbox: 
|   AP   |  AP50   |  AP75  |  APs  |  APm  |  APl   |
|:------:|:-------:|:------:|:-----:|:-----:|:------:|
| 63.886 | 100.000 | 78.238 |  nan  |  nan  | 63.886 |
[01/17 13:53:01 d2.evaluation.coco_evaluation]: Some metrics cannot be computed and is shown as NaN.
[01/17 13:53:01 d2.evaluation.coco_evaluation]: Per-category bbox AP: 
| category                  | AP     | category   | AP   | category   | AP   |
|:--------------------------|:-------|:-----------|:-----|:-----------|:-----|
| 0001                      | 63.886 | 0002       | nan  | 0003       | nan  |
| 0008                      | nan    | 0009       | nan  | 0010       | nan  |
| 0011                      | nan    | 0012       | nan  | 0013       | nan  |
| 0014                      | nan    | 0015       | nan  | 0016       | nan  |
| 0017                      | nan    | 0018       | nan  | 0126       | nan  |
| 1059                      | nan    | 1060       | nan  | 1061       | nan  |
| kisan_entire_dataset.json | nan    |            |      |            |      |
[01/17 13:53:01 d2.engine.defaults]: Evaluation results for kisan_val in csv format:
[01/17 13:53:01 d2.evaluation.testing]: copypaste: Task: bbox
[01/17 13:53:01 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[01/17 13:53:01 d2.evaluation.testing]: copypaste: 63.8864,100.0000,78.2383,nan,nan,63.8864
```
↓ 다시 학습이 진행됩니다.
```
[01/17 13:53:01 d2.utils.events]:  eta: 1 day, 2:28:49  iter: 999  total_loss: 0.3833  loss_cls: 0.04766  loss_box_reg: 0.2599  loss_rpn_cls: 0.007011  loss_rpn_loc: 0.03741  time: 0.9686  data_time: 0.1661  lr: 0.000999  max_mem: 11862M
[01/17 13:53:21 d2.utils.events]:  eta: 1 day, 2:31:02  iter: 1019  total_loss: 0.3489  loss_cls: 0.04653  loss_box_reg: 0.2353  loss_rpn_cls: 0.01009  loss_rpn_loc: 0.03919  time: 0.9696  data_time: 0.1712  lr: 0.001  max_mem: 11862M
[01/17 13:53:41 d2.utils.events]:  eta: 1 day, 2:31:46  iter: 1039  total_loss: 0.3155  loss_cls: 0.04232  loss_box_reg: 0.2427  loss_rpn_cls: 0.007752  loss_rpn_loc: 0.03226  time: 0.9703  data_time: 0.1684  lr: 0.001  max_mem: 11862M

..... (이하 생략)
```

train.py에서 제가 사용했던 설정 값은 아래와 같습니다.
```
def setup(args):
    """
    Create configs and perform basic setups.
    """
    cfg = get_cfg()
    cfg.merge_from_file(args.config_file)
    cfg.DATASETS.TRAIN = ("kisan_train",)
    cfg.DATASETS.TEST = ("kisan_val",)
    cfg.INPUT.MIN_SIZE_TRAIN = args.image_size[1]
    cfg.INPUT.MAX_SIZE_TRAIN = args.image_size[0]

    cfg.DATALOADER.NUM_WORKERS = 1
    cfg.SOLVER.IMS_PER_BATCH = 8
    cfg.SOLVER.BASE_LR = 0.001

    cfg.MODEL.ROI_HEADS.NUM_CLASSES = args.num_classes
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = (128)

    cfg.SOLVER.MAX_ITER = 100000

    cfg.SOLVER.CHECKPOINT_PERIOD = 1000
    cfg.TEST.EVAL_PERIOD = 1000

    # cfg.OUTPUT_DIR = f'/SSDc/kisane_DB/train_results'
    cfg.OUTPUT_DIR = f'/home/bak/Projects/Datasets/kisan_sample_data/train_results'
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)

    cfg.merge_from_list(args.opts)
    cfg.freeze()
    default_setup(cfg, args)
    return cfg

... (생략) ...

if __name__ == "__main__":
    args = default_argument_parser().parse_args()
    args.num_gpus = 1
    args.config_file = "configs/COCO-Detection/faster_rcnn_R_101_DC5_3x.yaml"
    args.image_size = [1280, 720]
    args.num_machines = 1

    print("Command Line Args:", args)
    launch(
        main,
        args.num_gpus,
        num_machines=args.num_machines,
        machine_rank=args.machine_rank,
        dist_url=args.dist_url,
        args=(args,),
    )
```

책임님께서 사용 중인 dataset 저장 위치가 `/home/kisan-dl-admin/kisan/AI_Scanner/gist/hdd1_data/datas/kisane_DB/`라면 임시로 다른 directory를 하나 만들고 data의 극히 일부(예를 들어 0001, 0094, 1032 만 복사)만 가져와서 따로 학습 진행 해 보시겠습니까?
(참고: 저에게는 dataset 저장위치가 `/home/bak/Projects/Datasets/kisan_sample_data` 였습니다.)

**Comment by hongyongje** [comment]
커밋: 342077d029e5d2ef9c87317e16f80c2c4fa0e673 [342077d]
상위 항목: f73dbc6595
작성자: psh9002 <psh9002@gmail.com>
날짜: 2023년 1월 17일 화요일 오후 12:55:33
커밋한 사람: psh9002
✨ skip unpaired data and save log


상기 리비전을 코드에 반영하고 (현재까지는) 학습이 잘 진행 중인 상태 입니다.

저희는 custom_mapper.py 에서
아래와 같이 data_dir='.' 으로 설정했는데 그럼 missing_data.json 이
kisan_entire_dataset.json, kisan_train.json, kisan_val.json 과 같은 경로에 생성 되는게 맞을까요?

```
if __name__ == "__main__":
    data_mapper = KisanDataMapper(data_dir='.', split='train')
```

질문드리는 이유는 missing_data.json 파일이 생성되지 않고 있는 것 같아서 입니다.

**Comment by psh9002** [comment]
제가 올려둔 코드에 의하면 모든 json파일이 같은 곳에 저장되는 것이 맞습니다.
```
            if 0 in self.missing_data:
                missing_data_log = self.data_dir + '/missing_data.json'
                with open(missing_data_log, 'w', encoding='utf-8') as f:
                    json.dump(self.missing_data, f, indent=4)
```

missing_data.json 은 RGB, GT, depth set이 온전히 없는 경우를 반환하도록 되어있습니다. 이러한 경우에 해당하는게 아예 존재하지 않는다면 missing_data.json자체를 생성하지 않도록 했습니다.
